export const MAPBOX_TOKEN = process.env.NEXT_PUBLIC_MAPBOX_TOKEN || "";

export const NEIGHBORHOOD = {
  name: "City of Ithaca",
  city: "Ithaca, NY",
  center: [-76.4969, 42.4440] as [number, number],
  address: "108 E Green St, Ithaca, NY 14850", // City Hall
  wards: 5,
  electionDistricts: 15,
};

// ─── Ward descriptions ────────────────────────────────────────────────────────
export const ITHACA_WARDS = [
  { ward: 1, name: "Ward 1",  description: "Downtown & Southside",   color: "#E8513A", legDist: "1" },
  { ward: 2, name: "Ward 2",  description: "West Hill & Heights",     color: "#F5C842", legDist: "2-3" },
  { ward: 3, name: "Ward 3",  description: "South Hill & East Hill",  color: "#4CAF82", legDist: "1,3" },
  { ward: 4, name: "Ward 4",  description: "Cornell & Northeast",     color: "#5BA4CF", legDist: "4" },
  { ward: 5, name: "Ward 5",  description: "Fall Creek & Inlet",      color: "#9B59B6", legDist: "2,5" },
];

// ─── Representatives — real Ithaca/Tompkins officials ─────────────────────────
export const representatives = [
  {
    id: "1",
    name: "Laura Lewis",
    role: "Mayor — City of Ithaca",
    initials: "LL",
    borderColor: "#E8513A",
    jurisdictionType: "Mayor",
    controls: [
      "City budget & capital projects",
      "Hiring city department heads",
      "Signing or vetoing Common Council legislation",
    ],
    donorAlert: null,
    votes: [
      { label: "Green New Deal Local Law",     aligned: true  },
      { label: "Rental housing inspection fee", aligned: false },
      { label: "Pedestrian safety overhaul",   aligned: true  },
    ],
    phone: "(607) 274-6501",
    email: "mayoroffice@cityofithaca.org",
    attendance: 96,
    topDonors: [
      { name: "Tompkins County Democrats", amount: 12000 },
      { name: "Labor Union PAC",           amount: 8500  },
      { name: "Local Business Coalition",  amount: 3200  },
    ],
    fullVotes: [
      { date: "Mar 15, 2024", bill: "Green New Deal Local Law — Phase 2", aligned: true,
        description: "Signed legislation banning gas appliances in new construction citywide" },
      { date: "Feb 28, 2024", bill: "Rental Housing Inspection Fee Increase", aligned: false,
        description: "Vetoed a fee hike on landlords for annual safety inspections — later overridden" },
      { date: "Jan 10, 2024", bill: "Pedestrian Safety Capital Plan $2.1M", aligned: true,
        description: "Signed $2.1M plan for crosswalk upgrades and protected bike lanes on State St" },
    ],
  },
  {
    id: "2",
    name: "Anna Kelles",
    role: "NY State Assembly — District 125",
    initials: "AK",
    borderColor: "#4CAF82",
    jurisdictionType: "State Assembly",
    controls: [
      "State funding for Ithaca housing & transit",
      "New York tenant protection legislation",
      "State environmental policy",
    ],
    donorAlert: null,
    votes: [
      { label: "Climate Leadership & Community Protection Act", aligned: true  },
      { label: "Good Cause Eviction statewide",                aligned: true  },
      { label: "Highway expansion funding",                    aligned: false },
    ],
    phone: "(607) 277-8679",
    email: "kellesA@nyassembly.gov",
    attendance: 97,
    topDonors: [
      { name: "NY Working Families Party", amount: 18000 },
      { name: "Sierra Club NY PAC",        amount: 7500  },
      { name: "SEIU 1199",                 amount: 6200  },
    ],
    fullVotes: [
      { date: "Apr 3, 2024", bill: "CLCPA Implementation Regulations", aligned: true,
        description: "Voted YES to accelerate 100% clean electricity grid target to 2035" },
      { date: "Mar 20, 2024", bill: "Good Cause Eviction — Statewide Extension", aligned: true,
        description: "Voted YES to extend tenant eviction protections to all New York municipalities" },
      { date: "Feb 14, 2024", bill: "Route 13 Widening Environmental Review Waiver", aligned: false,
        description: "Voted NO on waiving environmental review for Rt 13 expansion near Ithaca" },
    ],
  },
  {
    id: "3",
    name: "Lea Webb",
    role: "NY State Senate — District 52",
    initials: "LW",
    borderColor: "#F5C842",
    jurisdictionType: "State Senate",
    controls: [
      "State budget allocations for Tompkins County",
      "New York housing & infrastructure law",
      "Committee on Local Government",
    ],
    donorAlert: "$31k from real estate developers",
    votes: [
      { label: "Housing Compact — upzoning mandate", aligned: true  },
      { label: "Bail reform rollback",               aligned: false },
      { label: "Child tax credit expansion",         aligned: true  },
    ],
    phone: "(607) 735-9671",
    email: "webb@nysenate.gov",
    attendance: 93,
    topDonors: [
      { name: "Real Estate Board of NY PAC", amount: 31000 },
      { name: "NY State AFL-CIO",            amount: 14000 },
      { name: "Tompkins County Democrats",   amount: 9500  },
      { name: "Healthcare Workers United",   amount: 6800  },
    ],
    fullVotes: [
      { date: "Apr 10, 2024", bill: "NY Housing Compact — Transit-Oriented Zoning", aligned: true,
        description: "Voted YES to require municipalities near transit to allow denser housing" },
      { date: "Mar 5, 2024", bill: "Bail Reform Rollback — Expanded Detention List", aligned: false,
        description: "Voted NO on expanding list of crimes eligible for pre-trial detention" },
      { date: "Feb 22, 2024", bill: "Child & Dependent Care Tax Credit Expansion", aligned: true,
        description: "Voted YES to double the state child tax credit for families earning under $110k" },
    ],
  },
  {
    id: "4",
    name: "Marc Molinaro",
    role: "U.S. House — NY District 19",
    initials: "MM",
    borderColor: "#5BA4CF",
    jurisdictionType: "U.S. Congress",
    controls: [
      "Federal infrastructure funding for Ithaca",
      "National housing and community development grants",
      "Federal agriculture & rural programs",
    ],
    donorAlert: "$42k from real estate developers",
    votes: [
      { label: "Bipartisan Infrastructure Law",     aligned: true  },
      { label: "Affordable housing tax credit bill", aligned: false },
      { label: "Farm bill reauthorization",          aligned: true  },
    ],
    phone: "(607) 376-5025",
    email: "molinaro.house.gov/contact",
    attendance: 88,
    topDonors: [
      { name: "Real Estate Investment PAC", amount: 42000 },
      { name: "National Association of Realtors", amount: 21000 },
      { name: "NY Farm Bureau PAC",         amount: 11500 },
      { name: "Hudson Valley Business PAC", amount: 9200  },
    ],
    fullVotes: [
      { date: "Mar 28, 2024", bill: "Bipartisan Infrastructure & Jobs Act — Phase 2", aligned: true,
        description: "Voted YES on $1.2B in rural broadband and road funding for Upstate NY" },
      { date: "Mar 12, 2024", bill: "Affordable Housing Tax Credit Improvement Act", aligned: false,
        description: "Voted NO on expanding low-income housing tax credits (opposed by party)" },
      { date: "Feb 8, 2024", bill: "2024 Farm Bill Reauthorization", aligned: true,
        description: "Voted YES on $428B farm bill including nutrition programs and crop insurance" },
    ],
  },
];

// ─── Budget data (City of Ithaca FY2024 ~$75M operating budget) ───────────────
export const budgetData = [
  { name: "Public Safety",  value: 33, color: "#E06B5A", perResident: 1580, yoyChange: +3.2 },
  { name: "Public Works",   value: 18, color: "#5BA4CF", perResident: 862,  yoyChange: +1.4 },
  { name: "Parks & Rec",    value: 10, color: "#4CAF82", perResident: 479,  yoyChange: -1.8 },
  { name: "Planning",       value: 9,  color: "#1B2A4A", perResident: 431,  yoyChange: +0.6 },
  { name: "Administration", value: 14, color: "#F5C842", perResident: 670,  yoyChange: +2.1 },
  { name: "Community Dev.", value: 8,  color: "#9B59B6", perResident: 383,  yoyChange: +4.0 },
  { name: "Other",          value: 8,  color: "#A8B4B8", perResident: 383,  yoyChange: -0.3 },
];

export const equityComparison = [
  { category: "Parks",        yours: 479,  cityAvg: 820,  gap: -341 },
  { category: "Public Safety",yours: 1580, cityAvg: 1200, gap: +380 },
  { category: "Public Works", yours: 862,  cityAvg: 690,  gap: +172 },
  { category: "Community Dev",yours: 383,  cityAvg: 510,  gap: -127 },
  { category: "Planning",     yours: 431,  cityAvg: 360,  gap: +71  },
];

// ─── Community resources (real Ithaca locations) ──────────────────────────────
export const communityResources = [
  {
    id: "r1",
    category: "Homeless Shelters",
    icon: "🏠",
    name: "Ithaca Rescue Mission",
    address: "209 N Albany St, Ithaca, NY 14850",
    distance: "0.3 mi",
    hours: { today: "Open 24/7", isOpen: true },
    volunteerNeeds: "Meal servers, overnight volunteers, donation sorters",
    capacity: 65,
    maxCapacity: 90,
    volunteerDesc: "Help serve dinners, sort donations, or staff the overnight desk. Orientation is 45 minutes and scheduling is flexible.",
    timeCommitment: "3-hour shifts, weekly or bi-weekly",
    trainingRequired: false,
    phone: "(607) 273-2090",
    signupUrl: "#",
    lat: 42.4425,
    lng: -76.5000,
  },
  {
    id: "r2",
    category: "Food Banks",
    icon: "🍎",
    name: "Foodnet — Tompkins County",
    address: "260 Jason Pl, Ithaca, NY 14850",
    distance: "1.1 mi",
    hours: { today: "Mon–Fri 8am–4pm", isOpen: true },
    volunteerNeeds: "Food sorters, drivers, bilingual (Spanish) volunteers",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Sort and pack food boxes for the 8,000+ Tompkins County residents Foodnet serves each year. Drivers with cars especially needed.",
    timeCommitment: "2–4 hour shifts, flexible",
    trainingRequired: false,
    phone: "(607) 272-5270",
    signupUrl: "#",
    lat: 42.4328,
    lng: -76.4972,
  },
  {
    id: "r3",
    category: "Food Pantries",
    icon: "🍎",
    name: "Loaves & Fishes Free Café",
    address: "709 Hancock St, Ithaca, NY 14850",
    distance: "0.6 mi",
    hours: { today: "Mon Tue Thu 12–1pm", isOpen: false },
    volunteerNeeds: "Cooks, servers, prep volunteers Mon/Tue/Thu mornings",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Prepare and serve a free hot lunch to anyone who comes — no questions asked. A genuinely joyful place to volunteer.",
    timeCommitment: "9am–1pm on Mon, Tue, or Thu",
    trainingRequired: false,
    phone: "(607) 273-0456",
    signupUrl: "#",
    lat: 42.4398,
    lng: -76.4936,
  },
  {
    id: "r4",
    category: "Animal Shelters",
    icon: "🐾",
    name: "Tompkins County SPCA",
    address: "1640 Hanshaw Rd, Ithaca, NY 14850",
    distance: "2.4 mi",
    hours: { today: "Tue–Sun 11am–5pm", isOpen: true },
    volunteerNeeds: "Dog walkers, cat socializers, foster families urgently needed",
    capacity: 74,
    maxCapacity: 110,
    volunteerDesc: "Walk dogs, socialize cats waiting for adoption, or become a foster family. Training provided and the dogs are very good.",
    timeCommitment: "2+ hrs/week minimum",
    trainingRequired: true,
    phone: "(607) 257-1822",
    signupUrl: "#",
    lat: 42.4712,
    lng: -76.4710,
  },
  {
    id: "r5",
    category: "Clothing Donations",
    icon: "👕",
    name: "GreenStar Co-op Clothing Drive",
    address: "750 Cascadilla St, Ithaca, NY 14850",
    distance: "0.8 mi",
    hours: { today: "Wed–Sat 10am–4pm", isOpen: true },
    volunteerNeeds: "Sorters, intake volunteers, cashiers",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Sort donated clothing and household goods, assist shoppers, or run intake. All experience levels welcome. Great for groups.",
    timeCommitment: "Flexible, 3-hour shifts",
    trainingRequired: false,
    phone: "(607) 273-9392",
    signupUrl: "#",
    lat: 42.4361,
    lng: -76.4945,
  },
  {
    id: "r6",
    category: "Children & Family",
    icon: "👶",
    name: "Greater Ithaca Activities Center",
    address: "301 W Court St, Ithaca, NY 14850",
    distance: "0.4 mi",
    hours: { today: "Mon–Fri 8am–8pm", isOpen: true },
    volunteerNeeds: "Tutors (K-8), youth mentors, after-school program helpers",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Tutor students in reading and math, assist with GIAC's after-school programs, or mentor youth in the 10–17 age range.",
    timeCommitment: "2+ hrs/week, 8-week commitment for tutoring",
    trainingRequired: true,
    phone: "(607) 273-1511",
    signupUrl: "#",
    lat: 42.4400,
    lng: -76.5010,
  },
  {
    id: "r7",
    category: "Mental Health",
    icon: "🧠",
    name: "Tompkins County Mental Health Services",
    address: "201 E Green St, Ithaca, NY 14850",
    distance: "0.2 mi",
    hours: { today: "Mon–Fri 8:30am–4:30pm", isOpen: true },
    volunteerNeeds: "Peer support specialists, front-desk greeters, interpreters",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Greet and assist walk-in clients, help with paperwork, or serve as a peer support specialist if you have lived mental health experience.",
    timeCommitment: "4-hour shifts, flexible scheduling",
    trainingRequired: true,
    phone: "(607) 274-6200",
    signupUrl: "#",
    lat: 42.4398,
    lng: -76.4968,
  },
  {
    id: "r8",
    category: "Legal Aid",
    icon: "⚖️",
    name: "Legal Aid Society of Mid-New York — Ithaca",
    address: "120 E Buffalo St, Ithaca, NY 14850",
    distance: "0.5 mi",
    hours: { today: "Mon–Fri 9am–5pm", isOpen: true },
    volunteerNeeds: "Law students for intake, Spanish interpreters for tenant clinics",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Assist attorneys with client intake interviews, help with document translation, or conduct initial consultations for tenant rights cases.",
    timeCommitment: "8+ hrs/week preferred, law students welcome",
    trainingRequired: true,
    phone: "(607) 273-3667",
    signupUrl: "#",
    lat: 42.4390,
    lng: -76.4962,
  },
];

// ─── Map pins ─────────────────────────────────────────────────────────────────
export const mapPins = [
  {
    id: "m1",
    type: "meeting" as const,
    title: "Common Council Meeting",
    description: "Monthly council meeting — budget priorities & zoning votes",
    deadline: "Wed Apr 30 · 6:00 PM",
    action: "View agenda",
    lat: 42.4398,
    lng: -76.4969,
  },
  {
    id: "m2",
    type: "permit" as const,
    title: "120-Unit Mixed-Use on W State St",
    description: "6-story building proposed near Ithaca Commons — public comment open",
    deadline: "Comment by May 15",
    action: "Submit comment",
    lat: 42.4408,
    lng: -76.5020,
  },
  {
    id: "m3",
    type: "permit" as const,
    title: "Proposed Parking Garage Demolition",
    description: "Removal of Green St garage to enable housing site — EIS in progress",
    deadline: "Comment by May 8",
    action: "Submit comment",
    lat: 42.4385,
    lng: -76.4975,
  },
  {
    id: "m4",
    type: "resource" as const,
    title: "Ithaca Rescue Mission",
    description: "Emergency shelter — 65/90 capacity · Open 24/7",
    deadline: "Open now",
    action: "Get directions",
    lat: 42.4425,
    lng: -76.5000,
  },
  {
    id: "m5",
    type: "advocacy" as const,
    title: "Tenant Rights Clinic — Ithaca Tenants Union",
    description: "Free tenant rights help — every Tuesday 5–7pm",
    deadline: "Tuesdays 5–7pm",
    action: "View details",
    lat: 42.4410,
    lng: -76.4980,
  },
];

// ─── Upcoming events ──────────────────────────────────────────────────────────
export const upcomingEvents = [
  {
    id: "e1",
    type: "meeting",
    title: "Common Council Regular Meeting",
    description: "Monthly meeting. Agenda includes: West State St development environmental review, Green St garage decision, and 2025 budget preview.",
    attendance: "Attend at City Hall or watch on ithacany.gov/meetings",
    date: new Date("2024-04-30T18:00:00"),
    location: "Common Council Chambers, 108 E Green St",
  },
  {
    id: "e2",
    type: "meeting",
    title: "Ithaca Planning & Development Board",
    description: "Review of 120-unit mixed-use proposal on W State St. Site plan approval and affordable housing unit discussion.",
    attendance: "City Hall or zoom.ithacany.gov",
    date: new Date("2024-05-07T18:00:00"),
    location: "Common Council Chambers, 108 E Green St",
  },
  {
    id: "e3",
    type: "meeting",
    title: "Board of Public Works",
    description: "Vote on pedestrian safety improvements on State St and Aurora St. Discussion of Inlet Island park expansion.",
    attendance: "Public Works, 108 E Green St",
    date: new Date("2024-05-01T16:00:00"),
    location: "4th Floor Conference Room, City Hall",
  },
];

// ─── Open comment periods ─────────────────────────────────────────────────────
export const openComments = [
  {
    id: "c1",
    title: "120-Unit Mixed-Use at W State & S Plain St",
    description: "A developer is proposing a 6-story building with 120 apartments and ground-floor retail. Only 12 units (10%) would be affordable at 80% AMI. City's inclusionary zoning requires just 10%.",
    deadline: new Date("2024-05-15T17:00:00"),
    commentUrl: "#",
    urgent: false,
  },
  {
    id: "c2",
    title: "Green St Parking Garage Redevelopment",
    description: "The city is deciding whether to demolish the Green St garage to enable a mixed-income housing development. The site could yield 200+ units. Alternative: upgrade the garage for $18M.",
    deadline: new Date("2024-05-08T17:00:00"),
    commentUrl: "#",
    urgent: true,
  },
  {
    id: "c3",
    title: "Ithaca 2040 Comprehensive Plan Update",
    description: "The city's 20-year land use and growth plan is being updated. This shapes where housing gets built, how density is allowed, and how streets are redesigned for bikes and pedestrians.",
    deadline: new Date("2024-05-20T17:00:00"),
    commentUrl: "#",
    urgent: false,
  },
];

// ─── Recent votes ─────────────────────────────────────────────────────────────
export const recentVotes = [
  {
    id: "v1",
    title: "Green New Deal Local Law — Phase 2",
    description: "City banned gas appliances in all new construction. Ithaca becomes one of the first US cities to require all-electric buildings starting in 2025.",
    date: "Mar 15, 2024",
    result: "PASSED 9-1",
    aligned: true,
    votes: [
      { name: "Lewis (Mayor)", yes: true  },
      { name: "Brock (W1)",    yes: true  },
      { name: "Brown (W2)",    yes: true  },
      { name: "Gearhart (W3)",yes: false },
    ],
  },
  {
    id: "v2",
    title: "Rental Housing Inspection Fee Increase +$85",
    description: "Council voted to raise annual rental inspection fees from $65 to $150 to fund additional housing inspectors. Mayor vetoed — Council overrode the veto 8-2.",
    date: "Feb 28, 2024",
    result: "OVERRIDE 8-2",
    aligned: false,
    votes: [
      { name: "Lewis (Mayor)", yes: false },
      { name: "Brock (W1)",    yes: true  },
      { name: "Brown (W2)",    yes: true  },
      { name: "Ledger (W4)",   yes: true  },
    ],
  },
  {
    id: "v3",
    title: "Pedestrian Safety Capital Plan — $2.1M",
    description: "City approved $2.1M for protected bike lanes on State St, new crosswalk signals at 10 intersections, and curb extensions in the Commons area.",
    date: "Jan 10, 2024",
    result: "PASSED 10-0",
    aligned: true,
    votes: [
      { name: "Lewis (Mayor)", yes: true },
      { name: "Brock (W1)",    yes: true },
      { name: "Mehler (W5)",   yes: true },
      { name: "Gearhart (W3)",yes: true },
    ],
  },
];

// ─── Alerts ───────────────────────────────────────────────────────────────────
export const alerts = [
  {
    id: "a1",
    type: "red" as const,
    title: "Comment period closing in 48h",
    description: "Green St garage redevelopment — deadline May 8",
    action: "Comment now",
  },
  {
    id: "a2",
    type: "amber" as const,
    title: "Vote scheduled this week",
    description: "Common Council votes on W State St development — Apr 30",
    action: "Track vote",
  },
  {
    id: "a3",
    type: "green" as const,
    title: "Urgent volunteer need",
    description: "Tompkins County SPCA — foster families needed this weekend",
    action: "Sign up",
  },
  {
    id: "a4",
    type: "blue" as const,
    title: "Voter registration deadline",
    description: "Last day to register for June 25 Tompkins County primary — June 4",
    action: "Register",
  },
];

export const highlightVolunteer = communityResources[1]; // Foodnet
