export const MAPBOX_TOKEN = process.env.NEXT_PUBLIC_MAPBOX_TOKEN || "";

export const NEIGHBORHOOD = {
  name: "Temescal",
  city: "Oakland, CA",
  center: [-122.2654, 37.8375] as [number, number],
  address: "4218 Telegraph Ave, Oakland, CA 94609",
};

export const representatives = [
  {
    id: "1",
    name: "Nikki Fortunato Bas",
    role: "Oakland City Council — District 2",
    initials: "NB",
    borderColor: "#1B2A4A",
    jurisdictionType: "City Council",
    controls: [
      "City budget allocation for Temescal & Uptown",
      "Local zoning and development permits",
      "Police accountability and public safety policy",
    ],
    donorAlert: "$38k from real estate developers",
    votes: [
      { label: "Affordable housing mandate", aligned: true },
      { label: "Police overtime budget", aligned: false },
      { label: "Park restoration fund", aligned: true },
    ],
    phone: "(510) 238-7002",
    email: "district2@oaklandca.gov",
    attendance: 94,
    topDonors: [
      { name: "Real Estate PAC", amount: 38000 },
      { name: "Tech Industry Fund", amount: 12000 },
      { name: "Labor Council", amount: 8500 },
      { name: "Small Business Alliance", amount: 4200 },
    ],
    fullVotes: [
      { date: "Apr 2, 2024", bill: "Measure Q — Affordable Housing Bond", aligned: true, description: "Voted YES on $850M bond for affordable housing construction" },
      { date: "Mar 19, 2024", bill: "Police Overtime Budget Increase", aligned: false, description: "Voted YES on $4.2M increase to police overtime budget" },
      { date: "Mar 5, 2024", bill: "Temescal Park Restoration Fund", aligned: true, description: "Voted YES on $2.1M for park restoration in District 2" },
      { date: "Feb 20, 2024", bill: "Tenant Eviction Moratorium Extension", aligned: true, description: "Voted YES on 6-month extension of eviction moratorium" },
      { date: "Feb 6, 2024", bill: "Parking Meter Revenue Reallocation", aligned: false, description: "Voted YES to redirect meter revenue away from bike lanes" },
    ],
  },
  {
    id: "2",
    name: "Mia Bonta",
    role: "CA State Assembly — District 18",
    initials: "MB",
    borderColor: "#4A7C59",
    jurisdictionType: "State Assembly",
    controls: [
      "State funding for schools and healthcare",
      "California housing & tenant protection law",
      "State environmental regulations",
    ],
    donorAlert: null,
    votes: [
      { label: "AB 2011 — Affordable housing by right", aligned: true },
      { label: "Oil industry tax credit", aligned: true },
      { label: "School funding formula", aligned: true },
    ],
    phone: "(510) 286-1400",
    email: "assemblymember.bonta@assembly.ca.gov",
    attendance: 98,
    topDonors: [
      { name: "California Labor Federation", amount: 22000 },
      { name: "Education PAC", amount: 9800 },
      { name: "Environmental Advocates", amount: 7500 },
    ],
    fullVotes: [
      { date: "Apr 8, 2024", bill: "AB 2011 — Affordable Housing By Right", aligned: true, description: "Authored and voted YES to allow affordable housing on commercial land statewide" },
      { date: "Mar 25, 2024", bill: "Oil Industry Tax Credit Repeal", aligned: true, description: "Voted YES to end $800M in oil company subsidies" },
      { date: "Mar 11, 2024", bill: "Local School Funding Formula Fix", aligned: true, description: "Voted YES to direct $1.4B more to underfunded districts like Oakland Unified" },
    ],
  },
  {
    id: "3",
    name: "Barbara Lee",
    role: "U.S. Senator — California",
    initials: "BL",
    borderColor: "#E8A020",
    jurisdictionType: "U.S. Senate",
    controls: [
      "Federal housing and homelessness funding",
      "National healthcare and social safety net",
      "Foreign policy and federal appropriations",
    ],
    donorAlert: "$42k from real estate developers",
    votes: [
      { label: "Bipartisan Infrastructure Law", aligned: true },
      { label: "Defense budget increase", aligned: false },
      { label: "Child Tax Credit expansion", aligned: true },
    ],
    phone: "(510) 763-0370",
    email: "senator@barbaralee.com",
    attendance: 91,
    topDonors: [
      { name: "Real Estate Investment Trust PAC", amount: 42000 },
      { name: "Progressive Change Campaign", amount: 18000 },
      { name: "Healthcare Workers Union", amount: 14000 },
      { name: "Tech Employee PAC", amount: 11200 },
    ],
    fullVotes: [
      { date: "Apr 10, 2024", bill: "Bipartisan Infrastructure Investment Act", aligned: true, description: "Voted YES on $1.2T for roads, transit, clean energy" },
      { date: "Mar 28, 2024", bill: "National Defense Authorization Act", aligned: false, description: "Voted YES on $886B defense budget (one of few progressives to support)" },
      { date: "Mar 14, 2024", bill: "Child Tax Credit Expansion Act", aligned: true, description: "Voted YES to restore CTC to pandemic-era levels, lifting 3.7M children from poverty" },
    ],
  },
  {
    id: "4",
    name: "Layla Wahab",
    role: "OUSD School Board — District 2",
    initials: "LW",
    borderColor: "#E06B5A",
    jurisdictionType: "School Board",
    controls: [
      "Oakland Unified school closures and openings",
      "Curriculum and teaching staff decisions",
      "OUSD budget of $900M annually",
    ],
    donorAlert: null,
    votes: [
      { label: "Fremont High school closure reversal", aligned: true },
      { label: "Charter school expansion", aligned: false },
      { label: "Mental health counselor hiring", aligned: true },
    ],
    phone: "(510) 879-8000",
    email: "district2@ousd.org",
    attendance: 96,
    topDonors: [
      { name: "Oakland Education Association", amount: 15000 },
      { name: "Parent Coalition", amount: 4200 },
    ],
    fullVotes: [
      { date: "Apr 3, 2024", bill: "Fremont High School Closure Reversal", aligned: true, description: "Voted YES to reverse closure of Fremont High, keeping 800 students enrolled" },
      { date: "Mar 20, 2024", bill: "Charter School Expansion Waiver", aligned: false, description: "Voted NO on allowing 2 new charter schools in Temescal, citing enrollment impact" },
      { date: "Mar 6, 2024", bill: "Mental Health Counselor Hiring Initiative", aligned: true, description: "Voted YES to hire 40 additional mental health counselors district-wide" },
    ],
  },
];

export const budgetData = [
  { name: "Schools", value: 31, color: "#1B2A4A", perResident: 1240, yoyChange: +2.1 },
  { name: "Police & Fire", value: 28, color: "#E06B5A", perResident: 1120, yoyChange: +4.8 },
  { name: "Housing", value: 14, color: "#4A7C59", perResident: 560, yoyChange: -1.2 },
  { name: "Parks & Rec", value: 8, color: "#E8A020", perResident: 320, yoyChange: -3.1 },
  { name: "Roads", value: 9, color: "#7C5C9A", perResident: 360, yoyChange: +0.5 },
  { name: "Water & Sewer", value: 6, color: "#5B8DB8", perResident: 240, yoyChange: +1.8 },
  { name: "Other", value: 4, color: "#A8B4B8", perResident: 160, yoyChange: -0.4 },
];

export const equityComparison = [
  { category: "Parks", yours: 320, cityAvg: 660, gap: -340 },
  { category: "Schools", yours: 1240, cityAvg: 1380, gap: -140 },
  { category: "Roads", yours: 360, cityAvg: 290, gap: +70 },
  { category: "Housing Aid", yours: 560, cityAvg: 890, gap: -330 },
  { category: "Mental Health", yours: 44, cityAvg: 98, gap: -54 },
];

export const communityResources = [
  {
    id: "r1",
    category: "Homeless Shelters",
    icon: "🏠",
    name: "Crossroads Shelter",
    address: "3800 Telegraph Ave, Oakland",
    distance: "0.4 mi",
    hours: { today: "Open 24/7", isOpen: true },
    volunteerNeeds: "Weekend meal servers, donation sorters, night desk staff",
    capacity: 78,
    maxCapacity: 100,
    volunteerDesc: "Help serve meals, sort donations, or staff the overnight desk. No experience needed — just compassion and reliability.",
    timeCommitment: "4-hour shifts, weekly or bi-weekly",
    trainingRequired: false,
    phone: "(510) 555-0182",
    signupUrl: "#",
    lat: 37.835,
    lng: -122.265,
  },
  {
    id: "r2",
    category: "Food Banks",
    icon: "🍎",
    name: "Alameda County Community Food Bank",
    address: "7900 Edgewater Dr, Oakland",
    distance: "1.2 mi",
    hours: { today: "Mon–Fri 8am–5pm", isOpen: true },
    volunteerNeeds: "Food sorters, drivers with vans, bilingual Spanish/English volunteers",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Sort and pack food boxes, assist with client intake, or drive deliveries to seniors who can't travel.",
    timeCommitment: "3-hour shifts available",
    trainingRequired: false,
    phone: "(510) 635-3663",
    signupUrl: "#",
    lat: 37.83,
    lng: -122.272,
  },
  {
    id: "r3",
    category: "Food Pantries",
    icon: "🍎",
    name: "Temescal Community Pantry",
    address: "4701 Telegraph Ave, Oakland",
    distance: "0.6 mi",
    hours: { today: "Sat 9am–1pm", isOpen: false },
    volunteerNeeds: "Saturday morning volunteers, donation dropoff coordinators",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Help neighbors pick up weekly groceries and household supplies. Builds genuine relationships with community members.",
    timeCommitment: "4 hrs on Saturday mornings",
    trainingRequired: false,
    phone: "(510) 555-0247",
    signupUrl: "#",
    lat: 37.841,
    lng: -122.26,
  },
  {
    id: "r4",
    category: "Animal Shelters",
    icon: "🐾",
    name: "Oakland Animal Services",
    address: "1101 29th Ave, Oakland",
    distance: "2.1 mi",
    hours: { today: "Tue–Sat 10am–6pm", isOpen: true },
    volunteerNeeds: "Dog walkers, cat socializers, foster families urgently needed",
    capacity: 82,
    maxCapacity: 120,
    volunteerDesc: "Walk dogs, socialize cats, assist with adoptions, or become a foster family for animals awaiting placement.",
    timeCommitment: "2+ hrs/week minimum",
    trainingRequired: true,
    phone: "(510) 535-5602",
    signupUrl: "#",
    lat: 37.828,
    lng: -122.245,
  },
  {
    id: "r5",
    category: "Clothing Donations",
    icon: "👕",
    name: "St. Vincent de Paul Thrift & Donation",
    address: "2020 MacArthur Blvd, Oakland",
    distance: "1.5 mi",
    hours: { today: "Mon–Sat 9am–5pm", isOpen: true },
    volunteerNeeds: "Sorters, cashiers, donation intake — all skill levels",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Sort donated clothing, assist shoppers, or run the donation intake counter. Great for group volunteering.",
    timeCommitment: "Flexible — 3-6 hour shifts",
    trainingRequired: false,
    phone: "(510) 555-0312",
    signupUrl: "#",
    lat: 37.826,
    lng: -122.258,
  },
  {
    id: "r6",
    category: "Children & Family",
    icon: "👶",
    name: "Oakland Reach Family Resource Center",
    address: "3600 MLK Jr Way, Oakland",
    distance: "0.9 mi",
    hours: { today: "Mon–Fri 9am–6pm", isOpen: true },
    volunteerNeeds: "Tutors (K-8), childcare assistants, parent workshop facilitators",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Tutor students in reading and math, assist with after-school programs, or facilitate parenting workshops.",
    timeCommitment: "2+ hrs/week, minimum 8-week commitment for tutoring",
    trainingRequired: true,
    phone: "(510) 555-0401",
    signupUrl: "#",
    lat: 37.838,
    lng: -122.271,
  },
  {
    id: "r7",
    category: "Mental Health",
    icon: "🧠",
    name: "East Bay Mental Health Walk-In",
    address: "1900 Fruitvale Ave, Oakland",
    distance: "2.4 mi",
    hours: { today: "Daily 8am–8pm", isOpen: true },
    volunteerNeeds: "Peer support specialists, front desk greeters, multilingual interpreters",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Greet clients, assist with paperwork, or serve as a peer support specialist if you have lived experience with mental health challenges.",
    timeCommitment: "4-hour shifts, flexible days",
    trainingRequired: true,
    phone: "(510) 555-0509",
    signupUrl: "#",
    lat: 37.766,
    lng: -122.225,
  },
  {
    id: "r8",
    category: "Legal Aid",
    icon: "⚖️",
    name: "Bay Area Legal Aid — Oakland",
    address: "405 14th St, Oakland",
    distance: "1.8 mi",
    hours: { today: "Mon–Thu 9am–5pm", isOpen: true },
    volunteerNeeds: "Law students for intake, bilingual staff for tenant clinics",
    capacity: null,
    maxCapacity: null,
    volunteerDesc: "Assist attorneys with client intake, conduct initial consultations for tenant rights cases, or translate documents.",
    timeCommitment: "8+ hrs/week, law students preferred but not required",
    trainingRequired: true,
    phone: "(510) 982-1300",
    signupUrl: "#",
    lat: 37.804,
    lng: -122.272,
  },
];

export const mapPins = [
  {
    id: "m1",
    type: "meeting" as const,
    title: "District 2 Town Hall",
    description: "Monthly community meeting — budget priorities & development Q&A",
    deadline: "Thu Apr 25 · 6:30 PM",
    action: "View agenda",
    lat: 37.8395,
    lng: -122.2654,
  },
  {
    id: "m2",
    type: "meeting" as const,
    title: "OUSD Board Regular Meeting",
    description: "School board votes on Fremont High curriculum and budget",
    deadline: "Wed May 1 · 5:00 PM",
    action: "View agenda",
    lat: 37.8310,
    lng: -122.2720,
  },
  {
    id: "m3",
    type: "permit" as const,
    title: "47-Unit Mixed-Use Development",
    description: "New 6-story building at Telegraph & 43rd — public comment open",
    deadline: "Comment by May 10",
    action: "Submit comment",
    lat: 37.8410,
    lng: -122.2580,
  },
  {
    id: "m4",
    type: "permit" as const,
    title: "Temescal Alley Expansion",
    description: "Proposed closure of alley parking for outdoor dining activation",
    deadline: "Comment by Apr 30",
    action: "Submit comment",
    lat: 37.8368,
    lng: -122.2638,
  },
  {
    id: "m5",
    type: "resource" as const,
    title: "Crossroads Shelter",
    description: "Emergency shelter — 78/100 capacity · Open 24/7",
    deadline: "Open now",
    action: "Get directions",
    lat: 37.835,
    lng: -122.265,
  },
  {
    id: "m6",
    type: "resource" as const,
    title: "Temescal Community Pantry",
    description: "Free groceries · Saturdays 9am–1pm",
    deadline: "Opens Sat 9am",
    action: "Get directions",
    lat: 37.841,
    lng: -122.260,
  },
  {
    id: "m7",
    type: "advocacy" as const,
    title: "Oakland Tenants Union",
    description: "Free tenant rights counseling & eviction defense — weekly drop-in",
    deadline: "Tuesdays 5–8 PM",
    action: "View details",
    lat: 37.8340,
    lng: -122.2700,
  },
  {
    id: "m8",
    type: "advocacy" as const,
    title: "PUEBLO — People United for a Better Oakland",
    description: "Environmental justice organizing in Fruitvale & Temescal",
    deadline: "Meetings 1st Thursday",
    action: "View details",
    lat: 37.8280,
    lng: -122.2610,
  },
];

export const upcomingEvents = [
  {
    id: "e1",
    type: "meeting",
    title: "District 2 Town Hall",
    description: "Monthly community budget priorities meeting. City staff will present Q1 spending report. Public comment on Telegraph Ave streetscape improvements.",
    attendance: "Attend in person at Temescal Library or via Zoom",
    date: new Date("2024-04-25T18:30:00"),
    location: "Temescal Library, 5205 Telegraph Ave",
  },
  {
    id: "e2",
    type: "meeting",
    title: "Oakland Planning Commission",
    description: "Review of 47-unit mixed-use development at Telegraph & 43rd. Environmental impact assessment, affordable housing units discussion.",
    attendance: "City Hall, 1 Frank H. Ogawa Plaza, or livestreamed",
    date: new Date("2024-05-02T17:00:00"),
    location: "City Hall — Hearing Room 1",
  },
  {
    id: "e3",
    type: "meeting",
    title: "OUSD Board Regular Meeting",
    description: "Vote on mental health counselor hiring. Update on school consolidation plan. Public budget presentation for 2024–25.",
    attendance: "OUSD HQ or watch at ousd.org/board",
    date: new Date("2024-05-01T17:00:00"),
    location: "OUSD HQ, 1000 Broadway",
  },
];

export const openComments = [
  {
    id: "c1",
    title: "47-Unit Mixed-Use at Telegraph & 43rd",
    description: "A developer is proposing a 6-story building with 47 apartments and ground-floor retail. Only 5 units will be affordable at 80% AMI.",
    deadline: new Date("2024-05-10T17:00:00"),
    commentUrl: "#",
    urgent: false,
  },
  {
    id: "c2",
    title: "Temescal Alley Outdoor Dining Activation",
    description: "The city proposes closing Temescal Alley to vehicles permanently to create a car-free outdoor dining corridor. Affects 12 existing businesses.",
    deadline: new Date("2024-04-30T17:00:00"),
    commentUrl: "#",
    urgent: true,
  },
  {
    id: "c3",
    title: "Oakland 2040 General Plan Update",
    description: "The city's 20-year land use and housing plan is being updated. This shapes where housing gets built, where parks go, and how streets are designed.",
    deadline: new Date("2024-05-15T17:00:00"),
    commentUrl: "#",
    urgent: false,
  },
];

export const recentVotes = [
  {
    id: "v1",
    title: "Measure Q — Affordable Housing Bond",
    description: "City approved $850M bond to fund construction of 4,500 affordable units over 10 years. Raises property taxes by ~$18/year per $100k of assessed value.",
    date: "Apr 2, 2024",
    result: "PASSED 6-2",
    aligned: true,
    votes: [
      { name: "Bas (D2)", yes: true },
      { name: "Gallo (D5)", yes: false },
      { name: "Kalb (D1)", yes: true },
      { name: "Fife (D4)", yes: true },
    ],
  },
  {
    id: "v2",
    title: "Police Overtime Budget +$4.2M",
    description: "Council approved increasing police overtime from $18M to $22.2M to address staffing shortages. Critics argue it doesn't address root causes of crime.",
    date: "Mar 19, 2024",
    result: "PASSED 5-3",
    aligned: false,
    votes: [
      { name: "Bas (D2)", yes: true },
      { name: "Gallo (D5)", yes: true },
      { name: "Kalb (D1)", yes: false },
      { name: "Thao (Mayor)", yes: true },
    ],
  },
  {
    id: "v3",
    title: "Tenant Eviction Moratorium Extension",
    description: "City extended COVID-era eviction protections for 6 more months, protecting ~8,000 households currently behind on rent from displacement.",
    date: "Feb 20, 2024",
    result: "PASSED 7-1",
    aligned: true,
    votes: [
      { name: "Bas (D2)", yes: true },
      { name: "Gallo (D5)", yes: true },
      { name: "Kalb (D1)", yes: true },
      { name: "Fife (D4)", yes: false },
    ],
  },
];

export const alerts = [
  {
    id: "a1",
    type: "red" as const,
    title: "Comment period closing in 48h",
    description: "Temescal Alley outdoor dining plan — deadline Apr 30",
    action: "Comment now",
  },
  {
    id: "a2",
    type: "amber" as const,
    title: "Vote scheduled this week",
    description: "OUSD board votes on 40 new mental health counselors — May 1",
    action: "Track vote",
  },
  {
    id: "a3",
    type: "green" as const,
    title: "Urgent volunteer need",
    description: "Oakland Animal Services — foster families needed this weekend",
    action: "Sign up",
  },
  {
    id: "a4",
    type: "blue" as const,
    title: "Voter registration deadline",
    description: "Last day to register for June 4 primary — May 20",
    action: "Register",
  },
];

export const highlightVolunteer = communityResources[3]; // Animal shelter — foster urgently needed
